additionalArguments:
  - "--certificatesresolvers.letsencrypt.acme.storage=/certs/temp.json"
  - "--certificatesresolvers.letsencrypt.acme.email=spikearndt@gmail.com"
  - "--certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=linodev4"
ports:
  web:
    redirectTo: websecure
env:
  - name: LINODE_TOKEN
    valueFrom:
      secretKeyRef:
        name: linode
        key: token
ingressRoute:
  dashboard:
    enabled: false
persistence:
  enabled: true
  path: /certs
  size: 128Mi
ports.websecure.tls:
  enabled: true
  certResolver: "letsencrypt"
  domains:
    - main: ngeniusgaming.us
      sans:
        - "*.ngeniusgaming.us"
    - main: admin.ngeniusgaming.us
      sans:
        - "*.admin.ngeniusgaming.us"
podSecurityContext:
  fsGroup: null # workaround described: https://github.com/traefik/traefik-helm-chart/issues/164#issuecomment-621345258